version: '3.8'

services:
  whisper-api:
    build: .
    container_name: whisper-api
    environment:
      - WHISPER_MODEL=base  # Use base model for 4GB RAM
      - API_KEY=${API_KEY:?ERR_API_KEY_NOT_SET}
      - PORT=8088
      - UPLOAD_DIR=/app/uploads
      - DEBUG=false
    ports:
      - "8088:8088"
    volumes:
      - uploads:/app/uploads
    restart: unless-stopped

volumes:
  uploads:
